### ISSUE TITLE
Upload Car handling suboptimal

### ISSUE THREAD

**Issue by port22** [JustaPenguin/assetto-server-manager#545] opened 2019-10-08 17:55 UTC
Perhaps I am doing something wrong, but every time I upload a unzipped car mod, it does not upload the skins too. Then, I must upload every single skin one after the other cause no bulk upload available,

Also, the import just takes the name of the unzipped folder (I uploaded that) , and then users see this car as not installed.
Happened to me with the RSS Formula RSS 3 V6 from Race Sim Studio (https://sellfy.com/p/Cmuc/).
The content/cars folder of the unzipped archive contains the correct name of the car.

**Comment by Hecrer** [comment] 2019-10-09 11:14
Uploading a car definitely uploads the skins for me, although it may be related to the following:

If a car is uploaded with extra content (like the RSS 3 is) then you should upload the cars folder that you mentioned (content/cars) rather than the whole folder structure. That cars folder has a strict structure in order to work with AC that we also work with, but outside of it modders can do whatever they want, so we can't consistently work with whatever folder structure they've decided to go with.

Try just uploading that folder and see if it solves the skins problem!

**Comment by cheesegrits** [comment] 2019-10-11 17:19
I'm running a series with the RSS3 atm (awesome car) it worked OK for me just dragging and dropping the content/cars/rss_formula_rss_3_v6 folder from my local Assetto server folder for the car, with the stock skins plus a bunch of our league member's custom skins.

**Comment by cj123** [comment] 2020-01-21 16:06
I'm assuming that no follow up on this means the issue is sorted. closing!

**Closed by cj123** 2020-01-21 16:06 UTC
